apiVersion: apps/v1
kind: Deployment
metadata:
  name: smbapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smbapp
  template:
    metadata:
      labels:
        app: smbapp
    spec:
      containers:
      - name: smbapp
        image: smbapp
        resources: {}