apiVersion: skaffold/v2beta29
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: smbapp
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - app.yaml